<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class TransactionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $transactions = [
            [
                'transaction_date'=>'2024-05-20',
                'user_id'=>1,
                'recyclebank_id'=>1,
                'servtype_id'=>1,
                'wastetype_id'=>2,
                'waste_weight'=>550,
                'points_earned'=>5500,
            ],
            [
                'transaction_date'=>'2024-05-23',
                'user_id'=>2,
                'recyclebank_id'=>2,
                'servtype_id'=>2,
                'wastetype_id'=>3,
                'waste_weight'=>350,
                'points_earned'=>7000,
            ],
            [
                'transaction_date'=>'2024-06-13',
                'user_id'=>2,
                'recyclebank_id'=>2,
                'servtype_id'=>2,
                'wastetype_id'=>3,
                'waste_weight'=>320,
                'points_earned'=>6400,
            ],
            [
                'transaction_date'=>'2024-05-30',
                'user_id'=>3,
                'recyclebank_id'=>2,
                'servtype_id'=>1,
                'wastetype_id'=>2,
                'waste_weight'=>600,
                'points_earned'=>6000,
            ],
            [
                'transaction_date'=>'2024-06-04',
                'user_id'=>3,
                'recyclebank_id'=>2,
                'servtype_id'=>1,
                'wastetype_id'=>1,
                'waste_weight'=>300,
                'points_earned'=>15000,
            ],
            [
                'transaction_date'=>'2024-06-05',
                'user_id'=>3,
                'recyclebank_id'=>2,
                'servtype_id'=>1,
                'wastetype_id'=>1,
                'waste_weight'=>200,
                'points_earned'=>10000,
            ],
            [
                'transaction_date'=>'2024-06-07',
                'user_id'=>3,
                'recyclebank_id'=>3,
                'servtype_id'=>2,
                'wastetype_id'=>1,
                'waste_weight'=>1500,
                'points_earned'=>75000,
            ],
            [
                'transaction_date'=>'2024-06-07',
                'user_id'=>3,
                'recyclebank_id'=>1,
                'servtype_id'=>1,
                'wastetype_id'=>3,
                'waste_weight'=>100,
                'points_earned'=>2000,
            ],
            [
                'transaction_date'=>'2024-06-13',
                'user_id'=>3,
                'recyclebank_id'=>1,
                'servtype_id'=>1,
                'wastetype_id'=>1,
                'waste_weight'=>956,
                'points_earned'=>47800,
            ],
            [
                'transaction_date'=>'2024-06-15',
                'user_id'=>3,
                'recyclebank_id'=>1,
                'servtype_id'=>1,
                'wastetype_id'=>1,
                'waste_weight'=>78,
                'points_earned'=>3900,
            ],
        ];
        DB::table('transactions')->insert($transactions);
    }
}
